### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by DimonYoing** [BeeAZ-pm-pl/NightVision#1]
Can you please shorten the command to /vision please

**Comment by DimonYoing** [comment]
And please add so that others can also be given night vision

**Comment by DimonYoing** [comment]
and so that when you write /vision, you can set the time in seconds right in the chat

**Comment by DimonYoing** [comment]
That is, I write /vision <player> <time in second>

**Comment by BeeAZ-pm-pl** [comment]
ok

**Comment by DimonYoing** [comment]
And will you please do so that I can give another player night vision please

**Comment by BeeAZ-pm-pl** [comment]
install PurePerm

**Comment by DimonYoing** [comment]
No, you didn't understand I mean that /vision (player) (time)

**Comment by DimonYoing** [comment]
(Time in second(

**Comment by DimonYoing** [comment]
)*

**Comment by DimonYoing** [comment]
So that I can give this effect to another

**Comment by BeeAZ-pm-pl** [comment]
Set time in config

**Comment by DimonYoing** [comment]
How can I give a player night vision through the command /vision ?

**Comment by DimonYoing** [comment]
Can you make the effect be removed by the same command?

**Comment by DimonYoing** [comment]
Please?
